name: Claude Code Review

on:
  issue_comment:
    types: [created]
  pull_request:
    types: [labeled]

jobs:
  claude-review:
    if: |
      (github.event_name == 'issue_comment' && 
       github.event.issue.pull_request &&
       contains(github.event.comment.body, '@claude-review')) ||
      (github.event_name == 'pull_request' &&
       github.event.label.name == 'claude-review')

    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write
      id-token: write
      actions: read

    steps:
      - name: Add eye reaction to acknowledge comment
        if: github.event_name == 'issue_comment'
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.reactions.createForIssueComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: context.payload.comment.id,
              content: 'eyes'
            })

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event_name == 'issue_comment' && format('refs/pull/{0}/head', github.event.issue.number) || github.event.pull_request.head.ref }}
          fetch-depth: 1

      - name: Set PR number
        id: pr-number
        run: |
          if [ "${{ github.event_name }}" == "issue_comment" ]; then
            echo "number=${{ github.event.issue.number }}" >> $GITHUB_OUTPUT
          else
            echo "number=${{ github.event.pull_request.number }}" >> $GITHUB_OUTPUT
          fi

      - name: Run Claude Code Review
        id: claude-review
        uses: anthropics/claude-code-action@v1
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          additional_permissions: |
            actions: read
          prompt: |
            Review PR #${{ steps.pr-number.outputs.number }}.

            1. Post TODO list: code quality, bugs, performance, security, tests, CLAUDE.md adherence, summary
            2. Review using `gh pr diff/view`. Follow CLAUDE.md guidelines. Update TODO as you progress with `gh pr comment --edit-last`
            3. Replace TODO list with final summary using `gh pr comment --edit-last`: assessment, findings, code issues, highlights, action items

            Be constructive and specific.
          claude_args: '--allowed-tools "Bash(gh issue view:*),Bash(gh issue comment:*),Bash(gh pr comment:*),Bash(gh pr diff:*),Bash(gh pr view:*),Bash(gh pr list:*)"'
